name: Submit B12 Application

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  submit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: pip install requests
      
      - name: Submit application
        env:
          NAME: ${{ secrets.APPLICANT_NAME }}
          EMAIL: ${{ secrets.APPLICANT_EMAIL }}
          RESUME_LINK: ${{ secrets.RESUME_LINK }}
          REPOSITORY_LINK: ${{ github.server_url }}/${{ github.repository }}
          ACTION_RUN_LINK: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: python submit_application.py
